<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315145522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE `admin` CHANGE nom nom VARCHAR(255) DEFAULT NULL, CHANGE prenom prenom VARCHAR(255) DEFAULT NULL, CHANGE telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE first_name first_name VARCHAR(255) DEFAULT NULL, CHANGE last_name last_name VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE payment_status payment_status VARCHAR(255) DEFAULT NULL, CHANGE id_number id_number VARCHAR(255) DEFAULT NULL, CHANGE civilite civilite VARCHAR(255) DEFAULT NULL, CHANGE gender gender VARCHAR(50) DEFAULT NULL, CHANGE birth_date birth_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE birth_place birth_place VARCHAR(255) DEFAULT NULL, CHANGE nationality nationality VARCHAR(100) DEFAULT NULL, CHANGE marital_status marital_status VARCHAR(100) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE pays pays VARCHAR(100) DEFAULT NULL, CHANGE neighborhood neighborhood VARCHAR(255) DEFAULT NULL, CHANGE id_issue_date id_issue_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE license_number license_number VARCHAR(255) DEFAULT NULL, CHANGE education_level education_level VARCHAR(255) DEFAULT NULL, CHANGE profession profession VARCHAR(255) DEFAULT NULL, CHANGE income_bracket income_bracket VARCHAR(255) DEFAULT NULL, CHANGE housing_status housing_status VARCHAR(255) DEFAULT NULL, CHANGE primary_bank_account primary_bank_account VARCHAR(255) DEFAULT NULL, CHANGE discovery_channel discovery_channel VARCHAR(255) DEFAULT NULL, CHANGE previous_credit_experience previous_credit_experience VARCHAR(255) DEFAULT NULL, CHANGE repayment_source repayment_source VARCHAR(255) DEFAULT NULL, CHANGE id_scan_url id_scan_url VARCHAR(255) DEFAULT NULL, CHANGE license_scan_url license_scan_url VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE amount_paid amount_paid DOUBLE PRECISION DEFAULT NULL, CHANGE total_amount total_amount DOUBLE PRECISION DEFAULT NULL, CHANGE caution_amount caution_amount DOUBLE PRECISION DEFAULT NULL, CHANGE next_payment_amount next_payment_amount DOUBLE PRECISION DEFAULT NULL, CHANGE unpaid_amount unpaid_amount DOUBLE PRECISION DEFAULT NULL, CHANGE wallet_balance wallet_balance DOUBLE PRECISION DEFAULT NULL, CHANGE fines fines DOUBLE PRECISION DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE total_amount total_amount DOUBLE PRECISION DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE paid_amount paid_amount DOUBLE PRECISION DEFAULT NULL, CHANGE caution caution DOUBLE PRECISION DEFAULT NULL, CHANGE next_payment_amount next_payment_amount DOUBLE PRECISION DEFAULT NULL, CHANGE unpaid_amount unpaid_amount DOUBLE PRECISION DEFAULT NULL, CHANGE projected_margin projected_margin DOUBLE PRECISION DEFAULT NULL, CHANGE start_date start_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE end_date end_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE payment_status payment_status VARCHAR(100) DEFAULT NULL, CHANGE progress_percentage progress_percentage DOUBLE PRECISION DEFAULT NULL, CHANGE risk_level risk_level VARCHAR(100) DEFAULT NULL, CHANGE usage_type usage_type VARCHAR(255) DEFAULT NULL, CHANGE payment_frequency payment_frequency VARCHAR(100) DEFAULT NULL, CHANGE daily_rate daily_rate DOUBLE PRECISION DEFAULT NULL, CHANGE initial_deposit initial_deposit DOUBLE PRECISION DEFAULT NULL, CHANGE maintenance_and_insurance maintenance_and_insurance VARCHAR(255) DEFAULT NULL, CHANGE penalty_rate penalty_rate DOUBLE PRECISION DEFAULT NULL, CHANGE lieu lieu VARCHAR(255) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE ext_log_entries CHANGE object_id object_id VARCHAR(64) DEFAULT NULL, CHANGE data data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', CHANGE username username VARCHAR(191) DEFAULT NULL');
        $this->addSql('ALTER TABLE file CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE folder CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE general_setting CHANGE penalite_retard_journaliere penalite_retard_journaliere DOUBLE PRECISION DEFAULT NULL, CHANGE apport_initial_pourcentage apport_initial_pourcentage DOUBLE PRECISION DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE maintenance CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE date_intervention date_intervention DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE kilometrage kilometrage DOUBLE PRECISION DEFAULT NULL, CHANGE cost cost DOUBLE PRECISION DEFAULT NULL, CHANGE provider provider VARCHAR(150) DEFAULT NULL, CHANGE status status VARCHAR(100) DEFAULT NULL, CHANGE next_maintenance_date next_maintenance_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE technician technician VARCHAR(255) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE maintenance_alert CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE severity severity VARCHAR(100) DEFAULT NULL, CHANGE status status VARCHAR(100) DEFAULT NULL, CHANGE repair_cost repair_cost DOUBLE PRECISION DEFAULT NULL, CHANGE driver_info driver_info VARCHAR(255) DEFAULT NULL, CHANGE police_report_url police_report_url VARCHAR(255) DEFAULT NULL, CHANGE photos_urls photos_urls JSON DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE notification_setting CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE path CHANGE chemin chemin VARCHAR(255) DEFAULT NULL, CHANGE libelle libelle VARCHAR(255) DEFAULT NULL, CHANGE nom nom VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE permission permission VARCHAR(255) DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE payment CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE period period VARCHAR(100) DEFAULT NULL, CHANGE method method VARCHAR(100) DEFAULT NULL, CHANGE status status VARCHAR(100) DEFAULT NULL, CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE recorded_by recorded_by VARCHAR(255) DEFAULT NULL, CHANGE receipt_url receipt_url VARCHAR(255) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE penalty CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE amount amount DOUBLE PRECISION DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE due_date due_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE status status VARCHAR(100) DEFAULT NULL, CHANGE severity severity VARCHAR(100) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE refresh_token CHANGE id id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE role CHANGE nom nom VARCHAR(255) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE civilite civilite VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(50) DEFAULT NULL, CHANGE avatar avatar VARCHAR(255) DEFAULT NULL, CHANGE nom nom VARCHAR(255) DEFAULT NULL, CHANGE prenom prenom VARCHAR(255) DEFAULT NULL, CHANGE telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle ADD including_insurance TINYINT(1) DEFAULT NULL, ADD including_gps TINYINT(1) DEFAULT NULL, CHANGE immatriculation immatriculation VARCHAR(255) DEFAULT NULL, CHANGE marque marque VARCHAR(255) DEFAULT NULL, CHANGE modele modele VARCHAR(255) DEFAULT NULL, CHANGE couleur couleur VARCHAR(255) DEFAULT NULL, CHANGE finition finition VARCHAR(255) DEFAULT NULL, CHANGE numero_chassis numero_chassis VARCHAR(255) DEFAULT NULL, CHANGE carburant carburant VARCHAR(255) DEFAULT NULL, CHANGE transmission transmission VARCHAR(255) DEFAULT NULL, CHANGE categorie categorie VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE payment_status payment_status VARCHAR(255) DEFAULT NULL, CHANGE gps_status gps_status VARCHAR(255) DEFAULT NULL, CHANGE date_derniere_maintenance date_derniere_maintenance DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', CHANGE reimbursement_progress reimbursement_progress DOUBLE PRECISION DEFAULT NULL, CHANGE pipeline_status pipeline_status VARCHAR(255) DEFAULT NULL, CHANGE pre_reserved_by pre_reserved_by VARCHAR(255) DEFAULT NULL, CHANGE prix_par_jour prix_par_jour DOUBLE PRECISION DEFAULT NULL, CHANGE prix_de_vente prix_de_vente DOUBLE PRECISION DEFAULT NULL, CHANGE tco_estime tco_estime DOUBLE PRECISION DEFAULT NULL, CHANGE marge_brute_previsionnelle marge_brute_previsionnelle DOUBLE PRECISION DEFAULT NULL, CHANGE carte_grise_url carte_grise_url VARCHAR(255) DEFAULT NULL, CHANGE assurance_url assurance_url VARCHAR(255) DEFAULT NULL, CHANGE visite_technique_url visite_technique_url VARCHAR(255) DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE uuid uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE `admin` CHANGE nom nom VARCHAR(255) DEFAULT \'NULL\', CHANGE prenom prenom VARCHAR(255) DEFAULT \'NULL\', CHANGE telephone telephone VARCHAR(255) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE client CHANGE name name VARCHAR(255) DEFAULT \'NULL\', CHANGE first_name first_name VARCHAR(255) DEFAULT \'NULL\', CHANGE last_name last_name VARCHAR(255) DEFAULT \'NULL\', CHANGE phone phone VARCHAR(255) DEFAULT \'NULL\', CHANGE email email VARCHAR(255) DEFAULT \'NULL\', CHANGE status status VARCHAR(255) DEFAULT \'NULL\', CHANGE payment_status payment_status VARCHAR(255) DEFAULT \'NULL\', CHANGE id_number id_number VARCHAR(255) DEFAULT \'NULL\', CHANGE civilite civilite VARCHAR(255) DEFAULT \'NULL\', CHANGE gender gender VARCHAR(50) DEFAULT \'NULL\', CHANGE birth_date birth_date DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE birth_place birth_place VARCHAR(255) DEFAULT \'NULL\', CHANGE nationality nationality VARCHAR(100) DEFAULT \'NULL\', CHANGE marital_status marital_status VARCHAR(100) DEFAULT \'NULL\', CHANGE city city VARCHAR(255) DEFAULT \'NULL\', CHANGE pays pays VARCHAR(100) DEFAULT \'NULL\', CHANGE neighborhood neighborhood VARCHAR(255) DEFAULT \'NULL\', CHANGE id_issue_date id_issue_date DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE license_number license_number VARCHAR(255) DEFAULT \'NULL\', CHANGE education_level education_level VARCHAR(255) DEFAULT \'NULL\', CHANGE profession profession VARCHAR(255) DEFAULT \'NULL\', CHANGE income_bracket income_bracket VARCHAR(255) DEFAULT \'NULL\', CHANGE housing_status housing_status VARCHAR(255) DEFAULT \'NULL\', CHANGE primary_bank_account primary_bank_account VARCHAR(255) DEFAULT \'NULL\', CHANGE discovery_channel discovery_channel VARCHAR(255) DEFAULT \'NULL\', CHANGE previous_credit_experience previous_credit_experience VARCHAR(255) DEFAULT \'NULL\', CHANGE repayment_source repayment_source VARCHAR(255) DEFAULT \'NULL\', CHANGE id_scan_url id_scan_url VARCHAR(255) DEFAULT \'NULL\', CHANGE license_scan_url license_scan_url VARCHAR(255) DEFAULT \'NULL\', CHANGE type type VARCHAR(100) DEFAULT \'NULL\', CHANGE amount_paid amount_paid DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_amount total_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE caution_amount caution_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE next_payment_amount next_payment_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE unpaid_amount unpaid_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE wallet_balance wallet_balance DOUBLE PRECISION DEFAULT \'NULL\', CHANGE fines fines DOUBLE PRECISION DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE contract CHANGE reference reference VARCHAR(255) DEFAULT \'NULL\', CHANGE total_amount total_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE status status VARCHAR(255) DEFAULT \'NULL\', CHANGE paid_amount paid_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE caution caution DOUBLE PRECISION DEFAULT \'NULL\', CHANGE next_payment_amount next_payment_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE unpaid_amount unpaid_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE projected_margin projected_margin DOUBLE PRECISION DEFAULT \'NULL\', CHANGE start_date start_date DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE end_date end_date DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE payment_status payment_status VARCHAR(100) DEFAULT \'NULL\', CHANGE progress_percentage progress_percentage DOUBLE PRECISION DEFAULT \'NULL\', CHANGE risk_level risk_level VARCHAR(100) DEFAULT \'NULL\', CHANGE usage_type usage_type VARCHAR(255) DEFAULT \'NULL\', CHANGE payment_frequency payment_frequency VARCHAR(100) DEFAULT \'NULL\', CHANGE daily_rate daily_rate DOUBLE PRECISION DEFAULT \'NULL\', CHANGE initial_deposit initial_deposit DOUBLE PRECISION DEFAULT \'NULL\', CHANGE maintenance_and_insurance maintenance_and_insurance VARCHAR(255) DEFAULT \'NULL\', CHANGE penalty_rate penalty_rate DOUBLE PRECISION DEFAULT \'NULL\', CHANGE lieu lieu VARCHAR(255) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE ext_log_entries CHANGE object_id object_id VARCHAR(64) DEFAULT \'NULL\', CHANGE data data LONGTEXT DEFAULT \'NULL\' COMMENT \'(DC2Type:array)\', CHANGE username username VARCHAR(191) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE file CHANGE type type VARCHAR(255) DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE folder CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE general_setting CHANGE penalite_retard_journaliere penalite_retard_journaliere DOUBLE PRECISION DEFAULT \'NULL\', CHANGE apport_initial_pourcentage apport_initial_pourcentage DOUBLE PRECISION DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE maintenance CHANGE reference reference VARCHAR(255) DEFAULT \'NULL\', CHANGE type type VARCHAR(255) DEFAULT \'NULL\', CHANGE date_intervention date_intervention DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetime_immutable)\', CHANGE kilometrage kilometrage DOUBLE PRECISION DEFAULT \'NULL\', CHANGE cost cost DOUBLE PRECISION DEFAULT \'NULL\', CHANGE provider provider VARCHAR(150) DEFAULT \'NULL\', CHANGE status status VARCHAR(100) DEFAULT \'NULL\', CHANGE next_maintenance_date next_maintenance_date DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE technician technician VARCHAR(255) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE maintenance_alert CHANGE type type VARCHAR(255) DEFAULT \'NULL\', CHANGE date date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetime_immutable)\', CHANGE severity severity VARCHAR(100) DEFAULT \'NULL\', CHANGE status status VARCHAR(100) DEFAULT \'NULL\', CHANGE repair_cost repair_cost DOUBLE PRECISION DEFAULT \'NULL\', CHANGE driver_info driver_info VARCHAR(255) DEFAULT \'NULL\', CHANGE police_report_url police_report_url VARCHAR(255) DEFAULT \'NULL\', CHANGE photos_urls photos_urls LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE notification_setting CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE path CHANGE chemin chemin VARCHAR(255) DEFAULT \'NULL\', CHANGE libelle libelle VARCHAR(255) DEFAULT \'NULL\', CHANGE nom nom VARCHAR(255) DEFAULT \'NULL\', CHANGE type type VARCHAR(255) DEFAULT \'NULL\', CHANGE permission permission VARCHAR(255) DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE payment CHANGE reference reference VARCHAR(255) DEFAULT \'NULL\', CHANGE amount amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE date date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetime_immutable)\', CHANGE period period VARCHAR(100) DEFAULT \'NULL\', CHANGE method method VARCHAR(100) DEFAULT \'NULL\', CHANGE status status VARCHAR(100) DEFAULT \'NULL\', CHANGE type type VARCHAR(100) DEFAULT \'NULL\', CHANGE recorded_by recorded_by VARCHAR(255) DEFAULT \'NULL\', CHANGE receipt_url receipt_url VARCHAR(255) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE penalty CHANGE reference reference VARCHAR(255) DEFAULT \'NULL\', CHANGE amount amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE date date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetime_immutable)\', CHANGE due_date due_date DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE status status VARCHAR(100) DEFAULT \'NULL\', CHANGE severity severity VARCHAR(100) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE refresh_token CHANGE id id BINARY(16) NOT NULL, CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE role CHANGE nom nom VARCHAR(255) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE `user` CHANGE civilite civilite VARCHAR(255) DEFAULT \'NULL\', CHANGE status status VARCHAR(50) DEFAULT \'NULL\', CHANGE avatar avatar VARCHAR(255) DEFAULT \'NULL\', CHANGE nom nom VARCHAR(255) DEFAULT \'NULL\', CHANGE prenom prenom VARCHAR(255) DEFAULT \'NULL\', CHANGE telephone telephone VARCHAR(255) DEFAULT \'NULL\', CHANGE email email VARCHAR(255) DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT \'NULL\', CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vehicle DROP including_insurance, DROP including_gps, CHANGE immatriculation immatriculation VARCHAR(255) DEFAULT \'NULL\', CHANGE marque marque VARCHAR(255) DEFAULT \'NULL\', CHANGE modele modele VARCHAR(255) DEFAULT \'NULL\', CHANGE couleur couleur VARCHAR(255) DEFAULT \'NULL\', CHANGE finition finition VARCHAR(255) DEFAULT \'NULL\', CHANGE numero_chassis numero_chassis VARCHAR(255) DEFAULT \'NULL\', CHANGE carburant carburant VARCHAR(255) DEFAULT \'NULL\', CHANGE transmission transmission VARCHAR(255) DEFAULT \'NULL\', CHANGE categorie categorie VARCHAR(255) DEFAULT \'NULL\', CHANGE statut statut VARCHAR(255) DEFAULT \'NULL\', CHANGE payment_status payment_status VARCHAR(255) DEFAULT \'NULL\', CHANGE gps_status gps_status VARCHAR(255) DEFAULT \'NULL\', CHANGE date_derniere_maintenance date_derniere_maintenance DATE DEFAULT \'NULL\' COMMENT \'(DC2Type:date_immutable)\', CHANGE reimbursement_progress reimbursement_progress DOUBLE PRECISION DEFAULT \'NULL\', CHANGE pipeline_status pipeline_status VARCHAR(255) DEFAULT \'NULL\', CHANGE pre_reserved_by pre_reserved_by VARCHAR(255) DEFAULT \'NULL\', CHANGE prix_par_jour prix_par_jour DOUBLE PRECISION DEFAULT \'NULL\', CHANGE prix_de_vente prix_de_vente DOUBLE PRECISION DEFAULT \'NULL\', CHANGE tco_estime tco_estime DOUBLE PRECISION DEFAULT \'NULL\', CHANGE marge_brute_previsionnelle marge_brute_previsionnelle DOUBLE PRECISION DEFAULT \'NULL\', CHANGE carte_grise_url carte_grise_url VARCHAR(255) DEFAULT \'NULL\', CHANGE assurance_url assurance_url VARCHAR(255) DEFAULT \'NULL\', CHANGE visite_technique_url visite_technique_url VARCHAR(255) DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE uuid uuid BINARY(16) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
    }
}
